version: "3"
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      
  obiex_api:
    depends_on:
      - mysql
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
   
volumes:
  mysql_data: